dist: bionic

language: go
go:
  - 1.x

jobs:
  include:
    - stage: test
      script: make test

    - stage: code check
      if: type = pull_request
      install: make bootstrap
      script: make staticcheck

    - stage: deploy docker
      if: type != pull_request
      services: docker
      env:
        - GITSHA=$TRAVIS_COMMIT
        - PLATFORMS="linux/amd64,linux/arm64,linux/arm/v7"
      install:
        - docker container run --rm --privileged multiarch/qemu-user-static --reset -p yes
        - docker container run -d --rm --name buildkitd --privileged moby/buildkit:latest
        - sudo docker container cp buildkitd:/usr/bin/buildctl /usr/local/bin/
        - export BUILDKIT_HOST="docker-container://buildkitd"
      script:
        - export VERSION=git-$(echo $GITSHA | cut -c 1-7)
      deploy:
        - provider: script
          script: bash ./scripts/ci_build_image.sh --push $TRAVIS_REPO_SLUG $VERSION latest
          on:
            repo: profefe/profefe
            branch: master
      before_deploy:
        - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      after_failure:
        - buildctl debug workers ls
        - docker container logs buildkitd

