
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.1.0"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.0"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.10.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/xerrors"

[[constraint]]
  name = "github.com/dgraph-io/badger"
  version = "1.6.0"
