
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/rs/xid"
  version = "^1.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/google/pprof"
